version: "3.8"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - eshop_network

  basket-service:
    build: ./Basket.API
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/basket_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  catalog-service:
    build: ./Catalog.API
    ports:
      - "8081:8081"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/catalog_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  client-service:
    build: ./ClientApp
    ports:
      - "8082:8082"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/client_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  eshop.apphost-service:
    build: ./eshop.AppHost
    ports:
      - "8083:8083"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/apphost_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  eventbus-service:
    build: ./EventBus
    ports:
      - "8085:8085"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/eventbus_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  ordering.api-service:
    build: ./Ordering.API
    ports:
      - "8091:8091"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/ordering_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  orderprocessor-service:
    build: ./OrderProcessor
    ports:
      - "8094:8094"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/orderprocessor_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  paymentprocessor-service:
    build: ./PaymentProcessor
    ports:
      - "8095:8095"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/paymentprocessor_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  webapp-service:
    build: ./WebApp
    ports:
      - "8096:8096"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/webapp_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  webapphooks.api-service:
    build: ./WebApphooks.API
    ports:
      - "8099:8099"  
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/webapphooks_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

networks:
  eshop_network:

volumes:
  db_data:
