services:
  basket-service:
    build: ./Basket.API
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=mysql://db:3306/user_db
    depends_on:
      - db

  catalog-service:
    build: ./Catalog.API
    ports:
      - "8081:8081"
    environment:
      - MYSQL_URL=mysql://db:3306/site_db
    depends_on:
      - db

  client-service:
    build: ./ClientApp
    ports:
      - "8082:8082"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  eshop.apphost-service:
    build: ./eshop.AppHost
    ports:
      - "8083:8083"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  eshop.servicedefaults-service:
    build: ./eshop.ServiceDefaults
    ports:
      - "8084:8084"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  eventbus-service:
    build: ./EventBus
    ports:
      - "8085:8085"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  eventbusrabbitmq-service:
    build: ./EventBusRabbitMQ
    ports:
      - "8086:8086"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  hybridapp-service:
    build: ./HybridApp
    ports:
      - "8087:8087"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  identity-service:
    build: ./Identity.API
    ports:
      - "8088:8088"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  integrationeventlogef-service:
    build: ./IntegrationEventLogEF
    ports:
      - "8089:8089"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  mobile.bff.shopping-service:
    build: ./Mobile.Bff.Shopping
    ports:
      - "8090:8090"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  ordering.api-service:
    build: ./Ordering.API
    ports:
      - "8091:8091"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  ordering.domain-service:
    build: ./Ordering.Domain
    ports:
      - "8092:8092"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  ordering.infrastructure-service:
    build: ./Ordering.Infrastructure
    ports:
      - "8093:8093"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  orderprocessor-service:
    build: ./OrderProcessor
    ports:
      - "8094:8094"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  paymentprocessor-service:
    build: ./PaymentProcessor
    ports:
      - "8095:8095"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  webapp-service:
    build: ./WebApp
    ports:
      - "8096:8096"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  webappcomponents-service:
    build: ./WebAppComponents
    ports:
      - "8097:8097"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  webapphookclient-service:
    build: ./WebApphookClient
    ports:
      - "8098:8098"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  webapphooks.api-service:
    build: ./WebApphooks.API
    ports:
      - "8098:8098"
    environment:
      - MYSQL_URL=mysql://db:3306/org_db
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=user_db
    ports:
      - "3306:3306"

