services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    ports:
      - "3306:3306"
    networks:
      - eshop_network

  basket-service:
    build: src/Basket.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/basket_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  catalog-service:
    build: src/Catalog.API/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/catalog_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  client-service:
    build: src/ClientApp/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/client_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  eshop.apphost-service:
    build: src/eshop.AppHost/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/apphost_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  eshop.servicedefaults-service:
    build: src/eshop.ServiceDefaults/Dockerfile
    ports:
      - "8084:8084"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/servicedefaults_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  eventbus-service:
    build: src/EventBus/Dockerfile
    ports:
      - "8085:8085"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/eventbus_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  eventbusrabbitmq-service:
    build: src/EventBusRabbitMQ/Dockerfile
    ports:
      - "8086:8086"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/eventbusrabbitmq_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  hybridapp-service:
    build: eShop/src/HybridApp/Dockerfile
    ports:
      - "8087:8087"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/hybridapp_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  identity-service:
    build: src/Identity.API/Dockerfile
    ports:
      - "8088:8088"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/identity_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  integrationeventlogef-service:
    build: src/IntegrationEventLogEF/Dockerfile
    ports:
      - "8089:8089"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/integrationeventlogef_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  mobile.bff.shopping-service:
    build: src/Mobile.Bff.Shopping/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/mobile.bff_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  ordering.api-service:
    build: src/Ordering.API/Dockerfile
    ports:
      - "8091:8091"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/ordering_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  ordering.domain-service:
    build: src/Ordering.Domain/Dockerfile
    ports:
      - "8092:8092"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/ordering.domain_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  ordering.infrastructure-service:
    build: src/Ordering.Infrastructure/Dockerfile
    ports:
      - "8093:8093"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/ordering.infrastructure_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network
  
  orderprocessor-service:
    build: src/OrderProcessor/Dockerfile
    ports:
      - "8094:8094"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/orderprocessor_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  paymentprocessor-service:
    build: src/PaymentProcessor/Dockerfile
    ports:
      - "8095:8095"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/paymentprocessor_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  webapp-service:
    build: src/WebApp/Dockerfile
    ports:
      - "8096:8096"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/webapp_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  webappcomponents-service:
    build: src/WebAppComponents/Dockerfile
    ports:
      - "8097:8097"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/webappcomponents_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  webapphookclient-service:
    build: src/WebApphookClient/Dockerfile
    ports:
      - "8098:8098"
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/webapphookclient_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

  webapphooks.api-service:
    build: src/WebApphooks.API/Dockerfile
    ports:
      - "8099:8099"  
    environment:
      - MYSQL_URL=mysql://root:secret@db:3306/webapphooks_db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eshop_network

networks:
  eshop_network:

volumes:
  db_data:
